// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEGmiiVbSnC8a23wS3Na8vzZv51ijz8Uk',
    appId: '1:465229715902:web:4235819c26f4f68f3701ef',
    messagingSenderId: '465229715902',
    projectId: 'quotes-app-e39a7',
    authDomain: 'quotes-app-e39a7.firebaseapp.com',
    storageBucket: 'quotes-app-e39a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeOpeIH0LRvHBli3VoSTp1-Qd8009v7A',
    appId: '1:465229715902:android:be4fc22ee1034e703701ef',
    messagingSenderId: '465229715902',
    projectId: 'quotes-app-e39a7',
    storageBucket: 'quotes-app-e39a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEd1KI8joeBlIEoaaf-K57ePqWHKrr3Ec',
    appId: '1:465229715902:ios:32db72263a86e9633701ef',
    messagingSenderId: '465229715902',
    projectId: 'quotes-app-e39a7',
    storageBucket: 'quotes-app-e39a7.appspot.com',
    iosClientId: '465229715902-4mfq8u2a4a8o7oadl9t3cjoih205hv30.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEd1KI8joeBlIEoaaf-K57ePqWHKrr3Ec',
    appId: '1:465229715902:ios:32db72263a86e9633701ef',
    messagingSenderId: '465229715902',
    projectId: 'quotes-app-e39a7',
    storageBucket: 'quotes-app-e39a7.appspot.com',
    iosClientId: '465229715902-4mfq8u2a4a8o7oadl9t3cjoih205hv30.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotesApp',
  );
}
